// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class BatchHauMpn
{
    public int BatchHauMpnid { get; set; }

    public DateTime? BatchImportDate { get; set; }

    public virtual ICollection<MedicineHauMpn> MedicineHauMpns { get; set; } = new List<MedicineHauMpn>();
}