// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class HealthCheckConfirmationThienLm
{
    public int HealthCheckConfirmationThienLmid { get; set; }

    public int? ParentId { get; set; }

    public int? StudentId { get; set; }

    public int? HealthCheckSessionThienLmid { get; set; }

    public DateTime? SubmitAt { get; set; }

    public string Description { get; set; }

    public bool? IsConfirmed { get; set; }

    public virtual ICollection<HealthCheckRecordThienLm> HealthCheckRecordThienLms { get; set; } = new List<HealthCheckRecordThienLm>();

    public virtual HealthCheckSessionThienLm HealthCheckSessionThienLm { get; set; }

    public virtual User Parent { get; set; }

    public virtual StudentsHoaLq Student { get; set; }
}