// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class HealthCheckRecordThienLm
{
    public int HealthCheckRecordThienLmid { get; set; }

    public int? StudentId { get; set; }

    public int? HealthCheckSessionThienLmid { get; set; }

    public int? HealthCheckConfirmationThienLmid { get; set; }

    public int? NurseId { get; set; }

    public DateTime? CheckedAt { get; set; }

    public decimal? Weight { get; set; }

    public decimal? Height { get; set; }

    public int? VisionScore { get; set; }

    public int? HearingScore { get; set; }

    public int? BloodPressure { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public virtual HealthCheckConfirmationThienLm HealthCheckConfirmationThienLm { get; set; }

    public virtual HealthCheckSessionThienLm HealthCheckSessionThienLm { get; set; }

    public virtual User Nurse { get; set; }

    public virtual StudentsHoaLq Student { get; set; }
}