// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class HealthCheckSessionThienLm
{
    public int HealthCheckSessionThienLmid { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public DateTime? StartAt { get; set; }

    public DateTime? EndAt { get; set; }

    public string Address { get; set; }

    public bool? Status { get; set; }

    public DateTime? RegistrationStartAt { get; set; }

    public DateTime? RegistrationEndAt { get; set; }

    public virtual ICollection<HealthCheckConfirmationThienLm> HealthCheckConfirmationThienLms { get; set; } = new List<HealthCheckConfirmationThienLm>();

    public virtual ICollection<HealthCheckRecordThienLm> HealthCheckRecordThienLms { get; set; } = new List<HealthCheckRecordThienLm>();
}