// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class HealthProfilesHoaLq
{
    public int HealthProfileHoaLqid { get; set; }

    [Required(ErrorMessage = "Please choose student")]
    public int StudentId { get; set; }

    [Range(0, 100, ErrorMessage = "Overweight, go away!")]
    public decimal? Weight { get; set; }

    public decimal? Height { get; set; }

    public int? Sight { get; set; }

    public int? Hearing { get; set; }

    public int? BloodPressure { get; set; }

    public string Allergy { get; set; }

    public string ChronicDisease { get; set; }

    public string MedicalHistory { get; set; }

    public string CurrentMedical { get; set; }

    public string BloodType { get; set; }

    public bool Sex { get; set; }
    [DataType(DataType.Date)]
    public DateOnly? DateOfBirth { get; set; }
    
    [JsonIgnore]
    public virtual StudentsHoaLq Student { get; set; }
}