// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class MedicalIncidentMedicinesDuyTv
{
    public int MedicalIncidentMedicinesDuyTvid { get; set; }

    public int? MedicalIncidentId { get; set; }

    public int? MedicineId { get; set; }

    public int? Quantity { get; set; }

    public string UsageNote { get; set; }

    public virtual MedicalIncidentsDuyTv MedicalIncident { get; set; }

    public virtual MedicineHauMpn Medicine { get; set; }
}