// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class MedicationOrderTraiNn
{
    public int Id { get; set; }

    public int? StudentId { get; set; }

    public int? ParentId { get; set; }

    public string TinhTrang { get; set; }

    public DateTime? CreateAt { get; set; }

    public int? NurseId { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<MedicationTraiNn> MedicationTraiNns { get; set; } = new List<MedicationTraiNn>();

    public virtual User Nurse { get; set; }

    public virtual User Parent { get; set; }

    public virtual StudentsHoaLq Student { get; set; }
}