// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class MedicineHauMpn
{
    public int MedicineHauMpnid { get; set; }

    public string MedicineName { get; set; }

    public string MedicineUsagePurpose { get; set; }

    public string MedicineUsageInstructions { get; set; }

    public string MedicineType { get; set; }

    public string MedicineManufactureDate { get; set; }

    public int? MedicineQuantity { get; set; }

    public string MedicineUnit { get; set; }

    public DateTime? MedicineExpirationDate { get; set; }

    public int? MedicineBatchHauMpnid { get; set; }

    public bool? MedicineStatus { get; set; }

    public virtual ICollection<MedicalIncidentMedicinesDuyTv> MedicalIncidentMedicinesDuyTvs { get; set; } = new List<MedicalIncidentMedicinesDuyTv>();

    public virtual BatchHauMpn MedicineBatchHauMpn { get; set; }
}