// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class MedicalIncidentsDuyTv
{
    public int MedicalIncidentDuyTvid { get; set; }

    public int? StudentId { get; set; }

    public int? NurseId { get; set; }

    public string IncidentType { get; set; }

    public string Symptoms { get; set; }

    public string Diagnosis { get; set; }

    public string Treatment { get; set; }

    public byte? SeverityLevel { get; set; }

    public bool? ParentNotification { get; set; }

    public bool? FollowUp { get; set; }

    public string FollowUpNote { get; set; }

    public DateTime? IncidentTime { get; set; }

    public virtual ICollection<MedicalIncidentMedicinesDuyTv> MedicalIncidentMedicinesDuyTvs { get; set; } = new List<MedicalIncidentMedicinesDuyTv>();

    public virtual User Nurse { get; set; }

    public virtual StudentsHoaLq Student { get; set; }
}