// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class StudentsHoaLq
{
    public int StudentsHoaLqid { get; set; }

    public string StudentCode { get; set; }

    public string StudentFullName { get; set; }

    public int? UserId { get; set; }

    public string SdtNguoigiamho { get; set; }

    public int? ClassId { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<HealthCheckConfirmationThienLm> HealthCheckConfirmationThienLms { get; set; } = new List<HealthCheckConfirmationThienLm>();

    public virtual ICollection<HealthCheckRecordThienLm> HealthCheckRecordThienLms { get; set; } = new List<HealthCheckRecordThienLm>();

    public virtual ICollection<HealthProfilesHoaLq> HealthProfilesHoaLqs { get; set; } = new List<HealthProfilesHoaLq>();

    public virtual ICollection<MedicalIncidentsDuyTv> MedicalIncidentsDuyTvs { get; set; } = new List<MedicalIncidentsDuyTv>();

    public virtual ICollection<MedicationOrderTraiNn> MedicationOrderTraiNns { get; set; } = new List<MedicationOrderTraiNn>();

    public virtual User User { get; set; }

    public virtual ICollection<VaccinationConsentFormsTinHt> VaccinationConsentFormsTinHts { get; set; } = new List<VaccinationConsentFormsTinHt>();

    public virtual ICollection<VaccinationRecordsTinHt> VaccinationRecordsTinHts { get; set; } = new List<VaccinationRecordsTinHt>();
}