// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class User
{
    public int UserId { get; set; }

    public int? RoleId { get; set; }

    public string UserName { get; set; }

    public string UserAddress { get; set; }

    public string UserPhone { get; set; }

    public string UserAccount { get; set; }

    public string UserHashPassword { get; set; }

    public virtual ICollection<HealthCheckConfirmationThienLm> HealthCheckConfirmationThienLms { get; set; } = new List<HealthCheckConfirmationThienLm>();

    public virtual ICollection<HealthCheckRecordThienLm> HealthCheckRecordThienLms { get; set; } = new List<HealthCheckRecordThienLm>();

    public virtual ICollection<MedicalIncidentsDuyTv> MedicalIncidentsDuyTvs { get; set; } = new List<MedicalIncidentsDuyTv>();

    public virtual ICollection<MedicationOrderTraiNn> MedicationOrderTraiNnNurses { get; set; } = new List<MedicationOrderTraiNn>();

    public virtual ICollection<MedicationOrderTraiNn> MedicationOrderTraiNnParents { get; set; } = new List<MedicationOrderTraiNn>();

    public virtual Role Role { get; set; }

    public virtual ICollection<StudentsHoaLq> StudentsHoaLqs { get; set; } = new List<StudentsHoaLq>();

    public virtual ICollection<VaccinationConsentFormsTinHt> VaccinationConsentFormsTinHts { get; set; } = new List<VaccinationConsentFormsTinHt>();

    public virtual ICollection<VaccinationRecordsTinHt> VaccinationRecordsTinHts { get; set; } = new List<VaccinationRecordsTinHt>();
}