// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class VaccineCampaignsTinHt
{
    public int VaccineCampaignTinHtid { get; set; }

    public string CampaignName { get; set; }

    public string CampaignDescription { get; set; }

    public DateTime? StartDateTime { get; set; }

    public DateTime? EndDateTime { get; set; }

    public string Location { get; set; }

    public string VaccineName { get; set; }

    public string VaccineDescription { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? RegistrationStartAt { get; set; }

    public DateTime? RegistrationEndAt { get; set; }

    public virtual ICollection<VaccinationConsentFormsTinHt> VaccinationConsentFormsTinHts { get; set; } = new List<VaccinationConsentFormsTinHt>();

    public virtual ICollection<VaccinationRecordsTinHt> VaccinationRecordsTinHts { get; set; } = new List<VaccinationRecordsTinHt>();
}