// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SchoolMedical.Repositories.HoaLQ.Models;

public partial class VaccinationRecordsTinHt
{
    public int VaccinationRecordTinHtid { get; set; }

    public int? StudentId { get; set; }

    public int? VaccineCampaignTinHtid { get; set; }

    public int? ConsentFormId { get; set; }

    public int? NurseId { get; set; }

    public string PreVaccinationCondition { get; set; }

    public DateTime? VaccinationDateTime { get; set; }

    public string PostVaccinationCondition { get; set; }

    public string AdverseSymptoms { get; set; }

    public bool? IsCompleted { get; set; }

    public virtual VaccinationConsentFormsTinHt ConsentForm { get; set; }

    public virtual User Nurse { get; set; }

    public virtual StudentsHoaLq Student { get; set; }

    public virtual VaccineCampaignsTinHt VaccineCampaignTinHt { get; set; }
}